name: hema
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  go_router: ^16.2.0
  provider: ^6.1.2
  firebase_core: ^4.4.0
  firebase_auth: '>=5.3.3'
  cloud_functions: ^6.0.0
  cloud_firestore: '>=5.5.0'
  file_picker: '>=8.1.2'
  http: ^1.0.0
  google_generative_ai: 0.4.7
  country_picker: ^2.0.0
  geoflutterfire_plus: 0.0.33
  app_settings: ^7.0.0
  intl: 0.20.2
  firebase_messaging: ^16.0.0
  flutter_local_notifications: ^18.0.0
  shared_preferences: ^2.0.0
  url_launcher: ^6.0.0
  firebase_storage: ^13.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/hema_icon.png
  image_path_ios_dark: assets/images/hema_icon_dark.png
  remove_alpha_ios: true
